learnwithchandan/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from blog.views import ShowPosts,ShowDetail
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',ShowPosts.as_view(),name='show_posts'),
    re_path(r'^(?P<pk>\d+)/$',ShowDetail.as_view(),name='post_detail'),
    # re_path(r'^(?P<pk>\d+)/$',commentform,name='form_view')

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class Post(models.Model):
  title=models.CharField(max_length=100)
  detail=models.TextField()
  image=models.ImageField(upload_to='image/',blank=True)
  author=models.CharField(max_length=100)
  draft=models.BooleanField(default=True)
  published_date=models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return self.title

  def get_absolute_url(self):
    return reverse('post_detail',kwargs={'pk':self.pk})


class Comment(models.Model):
  post=models.ForeignKey(Post,on_delete=models.CASCADE)
  name=models.CharField(max_length=100)
  email=models.EmailField(max_length=100)
  comment=models.TextField()
  commented_date=models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return self.name

blog/forms.py
from django import forms;
from . models import Comment


class CommentForm(forms.ModelForm):
  class Meta:
    model=Comment
    fields=('name','email','comment')

blog/views.py
from django.shortcuts import render,HttpResponseRedirect,HttpResponse,get_object_or_404
from  .models import Post,Comment
from django.views.generic import ListView,DetailView,TemplateView,CreateView,FormView
from django.views import View
from blog.forms import CommentForm
# Create your views here.

class ShowPosts(ListView):
  model=Post

class ShowDetail(DetailView):
  model=Post
  template_name='blog/post_detail.html'


class ShowComment(TemplateView):
  model=Comment
  template_name='blog/post_detail.html'

class CommentForms(FormView):
  template_name='blog/post_detail.html'
  form_class=CommentForm
  success_url='/'

  def form_valid(self,form):
    form.save()
    return HttpResponse("Thanks")

templates/blog/comments.html
{% block comments %}
            <h1>Write Your Comments</h1>
                <form method="GET">
                    {% csrf_token %}
                    {{form.as_table}}
                    <button type="submit">submit</button>
                </form>
            </div>
            <!-- end of comment area -->

            {% endblock%}

templates/blog/post_detail.html
{% extends 'blog/post_list.html' %}


{% block detail%}
   <!-- post detail section starts -->
    <section id="post-detail-section">
        <div class="post_detail_container">
            <div class="post_detail">
                    <div class="header-text">
                         <h1>{{post.title}}</h1> 
                    </div>
               
                <p><em>Posted By:{{post.author|title}},{{post.published_date|date}}</em></p>
                <div class="detail-texts">
                    {{post.detail|safe}}
                </div>
            </div>

                    <!-- comment area -->
        <div class="comments">
            <h1>Comments</h1>
                {% for comment in post.comment_set.all %}
                    <div class="pre-comments">
                        <div class="user-detail">
                            <p><b> {{comment.name}} </b></p>
                            <span><small>{{comment.commented_date|date}}</small></span>
                        </div>
                        <div class="comment-text">
                            {{comment.comment}}
                        </div>
                    </div>
                    {% empty %}
                    <p>NO COMMENTS YET.BE FIRST TO COMMENTS</p>
                {%endfor%}
                <h1>Write Your Comments</h1>
                
                <form method="POST">
                    {% csrf_token %}
                    {{form}}
                    <input type="submit" value="Comment">
                </form>
                

            </div>
            <!-- end of comment area -->
           
    
   <!-- end of post detail section -->
        </div>

           
        <!-- share section -->
        <div class="social-share-links">
                <a href=""><i class="fab fa-facebook-f"></i></a>
                <a href=""><i class="fab fa-linkedin-in"></i></a>
                <a href="">  <i class="fas fa-envelope"></i></a>       
            </div>
        <!-- end of share -->


   {% endblock %}

templates/blog/post_list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/design.css' %}">
    <link rel="stylesheet" href="{% static 'css/post-detail.css' %}">

    
    <!-- links for google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=EB+Garamond" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <title>Learnwithchandan</title>
</head>
<body>
    <!-- header section starts -->
    <header>
        <div id="logo"><a href={% url 'show_posts' %}>Learnwithchandan</a>
               <!-- for responsive -->
               <div class="mobile-icon">
                <a href="#" >
                    <i class="fas fa-bars"></i>
                </a>
            </div>
        </div>
        
        <hr/>
        <nav>
            <div class="navbar">
                <div class="nav-links">
                    <ul>
                        <li><a href="{% url 'show_posts'%}">Posts</a></li>
                        <li><a href="">Series</a></li>
                        <li><a href="">Research</a></li>
                        <li><a href="">Portfolio</a></li>

                    </ul>
                </div>
                <div class="Searchform">
                    <!-- for search -->
                    <form method="post" class="search" action={% url 'show_posts' %}>
                        {% csrf_token %}
                        <input type="text" name='q' placeholder="Search anything">
                        <input type="submit" value=Search>
                    </form>
                </div>
            </div>

         
        </nav>
    </header>
    
    <!-- end of header section -->

    <!-- post section starts -->
    
    <section id="post-section">
        <div class="blog-posts">
            <!-- post container -->
        
        <div class="post-container">
            
            <!-- for posts -->
            {% for post in post_list%}
                {% if post.draft is not True%}
                    <div class="posts">
                        <div class="image">                       
                            <img src="http://via.placeholder.com/200" alt="">  
                        </div>
                            <h1>{{post.title}}</h1>
                        <div class="description-text">
                            <p><small>learn python from novice</small></p>
                        </div>
                        <div class="read-more">
                            <a href={{post.get_absolute_url}}>Read More..</a>
                        </div>
                    </div> 
                {% endif%}
            {% endfor%}


            {% block detail%}

            {% endblock%}
            {% block comments%}
            
            {% endblock%}

            <!-- end post -->
        </div>
        <!-- end post-container -->
        </div>

        <div class="sidebar">
            <!-- search -->
        <!-- <div class="blog-search">
                <form action="" method="post">
                    <input type="text" placeholder="Search anything">
                    <button type="submit">Search</button>
                </form>
            </div> -->
            <!-- end of search -->
    
            <!-- starts of Latest posts -->
            <div class="latest-posts">
                <h1>LATEST POSTS</h1>
                <hr/>
                <div class="title-container">
                    <div class="titles">
                        <a href="">Machine Learning</a>
                    </div>
                    <div class="titles">
                        <a href="">Deep Learning</a>
                    </div>
                    <div class="titles">
                        <a href="">Image Processing</a>
                    </div>
                    <div class="titles">
                        <a href="">AI Learning</a>
                    </div>
                    <div class="titles">
                        <a href="">Voice Processing</a>
                    </div>
                </div>
            </div>
            <!-- end of latestpost section -->
    
            <!-- tags sections -->
            <h1 class="tags-header">Tags</h1>
                <hr/>
            <div class="tags-container">
                
                <div class="tags">
                    <a href="">#Python</a>
                </div>
                <div class="tags">
                    <a href="">#Machinelearning</a>
                </div>
                <div class="tags">
                    <a href="">#DeepLearning</a>
                </div>
                <div class="tags">
                    <a href="">#Javascript</a>
                </div>
                <div class="tags">
                    <a href="">#Django</a>
                </div>
            </div>
            <!-- ends of tag section -->
        </div>
    </section>

    <!-- side bar section -->
 
<!-- end of side-bar section -->
    <!-- <footer>
        &copy;chandansharma
    </footer> -->

</body>
<script src={% static 'js/mobile.js' %}></script>
</html>

templates/index.html
{% load static_files %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href={% static 'css/design.css' %}>
    
    <!-- links for google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=EB+Garamond" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <title>Learnwithchandan</title>
</head>
<body>
    <!-- header section starts -->
    <header>
        <div id="logo"><a href="">Learnwithchandan</a>
               <!-- for responsive -->
               <div class="mobile-icon">
                <a href="#" >
                    <i class="fas fa-bars"></i>
                </a>
            </div>
        </div>
        
        <hr/>
        <nav>
            <div class="navbar">
                <div class="nav-links">
                    <ul>
                        <li><a href="">Posts</a></li>
                        <li><a href="">Series</a></li>
                        <li><a href="">Research</a></li>
                        <li><a href="">Portfolio</a></li>

                    </ul>
                </div>
                <div class="Searchform">
                    <!-- for search -->
                    <form method="post" class="search">
                        <input type="text" placeholder="Search anything">
                        <button type="submit">Search</button>
                    </form>
                </div>
            </div>

         
        </nav>
    </header>
    
    <!-- end of header section -->

    <!-- post section starts -->
    
    <section id="post-section">
        <div class="blog-posts">
            <!-- post container -->
        
        <div class="post-container">
            
            <!-- for posts -->
            <div class="posts">
                <div class="image">
                    <img src="http://via.placeholder.com/200" alt="">
                </div>
                <h1>Python</h1>
                <div class="description-text">
                        <p><small>learn python from novice</small></p>
                </div>
                <div class="read-more">
                    <a href="detail.html">Read More..</a>
                </div>
            </div>
            <div class="posts">
                <div class="image">
                    <img src="http://via.placeholder.com/200" alt="">
                </div>
                <h1>Python</h1>
                <p><small>learn python from novice</small></p>
                <div class="read-more">
                    <a href="detail.html">Read More..</a>
                </div>
            </div>
            <div class="posts">
                <div class="image">
                    <img src="http://via.placeholder.com/200" alt="">
                </div>
                <h1>Python</h1>
                <p><small>learn python from novice </small></p>
                <div class="read-more">
                    <a href="detail.html">Read More..</a>
                </div>
            </div>

            <div class="posts">
                <div class="image">
                    <img src="http://via.placeholder.com/200" alt="">
                </div>
                <h1>Python</h1>
                <p><small>learn python from novice </small></p>
                <div class="read-more">
                    <a href="detail.html">Read More..</a>
                </div>
            </div>

            <div class="posts">
                <div class="image">
                    <img src="http://via.placeholder.com/200" alt="">
                </div>
                <h1>Python</h1>
                <p><small>learn python from novice </small></p>
                <div class="read-more">
                    <a href="detail.html">Read More..</a>
                </div>
            </div>
            <div class="posts">
                <div class="image">
                    <img src="http://via.placeholder.com/200" alt="">
                </div>
                <h1>Python</h1>
                <p><small>learn python from novice </small></p>
                <div class="read-more">
                    <a href="detail.html">Read More..</a>
                </div>
            </div>
            <!-- end post -->
        </div>
        <!-- end post-container -->
        </div>

        <div class="sidebar">
            <!-- search -->
        <div class="blog-search">
                <form action="" method="post">
                    <input type="text" placeholder="Search anything">
                    <button type="submit">Search</button>
                </form>
            </div>
            <!-- end of search -->
    
            <!-- starts of Latest posts -->
            <div class="latest-posts">
                <h1>LATEST POSTS</h1>
                <hr/>
                <div class="title-container">
                    <div class="titles">
                        <a href="">Machine Learning</a>
                    </div>
                    <div class="titles">
                        <a href="">Deep Learning</a>
                    </div>
                    <div class="titles">
                        <a href="">Image Processing</a>
                    </div>
                    <div class="titles">
                        <a href="">AI Learning</a>
                    </div>
                    <div class="titles">
                        <a href="">Voice Processing</a>
                    </div>
                </div>
            </div>
            <!-- end of latestpost section -->
    
            <!-- tags sections -->
            <h1 class="tags-header">Tags</h1>
                <hr/>
            <div class="tags-container">
                
                <div class="tags">
                    <a href="">#Python</a>
                </div>
                <div class="tags">
                    <a href="">#Machinelearning</a>
                </div>
                <div class="tags">
                    <a href="">#DeepLearning</a>
                </div>
                <div class="tags">
                    <a href="">#Javascript</a>
                </div>
                <div class="tags">
                    <a href="">#Django</a>
                </div>
            </div>
            <!-- ends of tag section -->
        </div>
    </section>

    <!-- side bar section -->
 
<!-- end of side-bar section -->
    <footer>
        &copy;chandansharma
    </footer>

</body>
<script src="js/mobile.js"></script>
</html>